from setuptools import setup, find_packages

setup(
    name="moriarty",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        'setuptools>=68.0.0',
        'opencv-python>=4.8.0',
        'mediapipe>=0.10.0',
        'numpy>=1.24.0',
        'tensorflow>=2.13.0',
        'scikit-learn>=1.3.0',
        'pandas>=2.0.0',
        'torch>=2.0.0',
        'torchvision>=0.15.0',
        'ray>=2.6.0',
        'dask>=2023.9.0',
        'distributed>=2023.9.0',
        'tqdm>=4.65.0',
        'multiprocess>=0.70.15',
        'langchain>=0.0.267',
        'langchain-openai>=0.0.2',
        'faiss-cpu>=1.7.4',
        'openai>=1.3.0',
        'tiktoken>=0.5.1',
        'python-dotenv>=1.0.0',
        'chromadb>=0.4.13',
        'pydantic>=2.0.0',
        'fastapi>=0.100.0',
        'uvicorn>=0.23.0',
        'pillow>=10.0.0',
        'psutil>=5.9.0',
        'transformers>=4.30.0',
        'datasets>=2.12.0',
        'accelerate>=0.20.0',
        'peft>=0.4.0',
        'anthropic>=0.2.6',
        'bitsandbytes>=0.40.0',
        'sentencepiece>=0.1.99',
        'tensorboard>=2.13.0',
        'matplotlib>=3.7.0',
        'requests>=2.31.0',
        'scipy>=1.11.0',
        'starlette>=0.27.0',
        'langchain-community>=0.0.10'
    ],
    author="Moriarty Team",
    description="A comprehensive sports video analysis system with pose estimation, biomechanical analysis, and AI-powered insights",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Multimedia :: Video",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    entry_points={
        "console_scripts": [
            "moriarty=src.main:main",
        ],
    },
) 